### PR TITLE
Fix GreeterService::stop

### LINKED ISSUE #464: Incorrect GreeterService::stop in C++
The C++ IceBox/greeter demo should be like the C# demo:

```cs
 public void stop()
    {
        Console.WriteLine($"{_greeterName} is shutting down...");

        // We destroy the object adapter in stop() in case the service is started, stopped and then restarted again
        // programmatically or using an admin tool.
        // The general rule is stop should cleanup all resources created by start.
        Debug.Assert(_adapter is not null);
        _adapter.destroy();
        _adapter = null;
    }
```

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes #464.

### CODE REVIEW

File: cpp/IceGrid/icebox/GreeterService.h [hunk 1]
```diff
@@ -23,7 +23,7 @@ namespace Service
         std::string _greeterName{"unknown"};
 
         // The object adapter created by this service.
-        Ice::ObjectAdapterPtr _adapter{nullptr};
```
Comment (bernardnormier) [inline cpp/IceGrid/icebox/GreeterService.h:26]: We typically don't/shouldn't initialize to the default value.

**Review by externl — APPROVED** [review]
